<?php
/**
 * @file
 * EntityReference Hidden module file.
 */

/**
 * Implements hook_menu().
 */
function entityreference_hidden_menu() {
  $items = array();

  $items['fields'] = array(
    'title' => 'Fields',
    'page callback' => 'entityreference_hidden_fields',
    'access arguments' => array('access content'),
  );

  return $items;
}

/**
 * Implements hook_field_widget_info_alter().
 */
function entityreference_hidden_field_widget_info_alter(&$info) {
  $info['hidden_hidden']['field types'][] = 'entityreference'; 
}

/**
 * Implements hook_field_alter().
 */
function entityreference_hidden_form_alter(&$form, &$form_state, $form_id) {
  if (isset($form['#entity']) && isset($form['#entity_type'])) {
    // Get Parent entity for fields.
    $field_parent_entity = isset($form['#entity']->type) ? $form['#entity']->type : NULL;
    // Get Parent entity type.
    $entity_type = $form['#entity_type'];
    // Get fields.
    $field_instances = field_info_instances($entity_type, $field_parent_entity);
    $field_lookup = array();
    // Find all entityreference fields that are hidden fields, assign them to
    // the field_lookup array.
    foreach ($field_instances as $field_name => $instance) {
      if (isset($instance['widget']) && $instance['widget']['type'] == 'hidden_hidden') {
        $field_lookup[] = $field_name;
      }
    }
    // If there are fields in field_lookup...
    if (!empty($field_lookup)) {
      // Get the URL query parameters.
      $query_parameters = drupal_get_query_parameters();
      foreach ($field_lookup as $field) {
        // If one of the fields is in the query parameters...
        if (isset($query_parameters[$field])) {
          // Get the language type for the entity instance.
          $language = $form['#entity']->language;
          // Check the default value of the entity reference in the form, and
          // set it to the query parameter if it is not set.
          if (!isset($form[$field][$language][0]['target_id']['#default_value'])) {
            $form[$field][$language][0]['target_id']['#default_value'] = $query_parameters[$field];
          }
          // If it is set, and the query parameters also have parameter
          // replace=yes, or the default value of the entity reference field is
          // set to 0, replace it with the query_parameter value for the field.
          elseif ((isset($form[$field][$language][0]['target_id']['#default_value']) &&
                  isset($query_parameters['replace']) &&
                  $query_parameters['replace'] == 'yes') || $form[$field][$language][0]['target_id']['#default_value'] == 0) {
            $form[$field][$language][0]['target_id']['#default_value'] = $query_parameters[$field];
          }
        }
      }
    }
  }
}
