<?php


/**
* Implements hook_menu().
*/
function artchimp_menu() {

  $items['settings/exhibition/%'] = array( 
    'title' => 'Select Works', 
    'description' => 'Artists works are listed here',
    'page callback' => 'drupal_get_form', 
    'page arguments' => array('artists_work_form'), 
    'access callback' => TRUE
  );

  return $items;
}

function artchimp_form_alter(&$form, &$form_state, $form_id) {
  //print_r($form_id);exit;
  global $user;
    switch ($form_id) {
      case "exhibition_node_form";
      $form['field_exhibition_hidden']['#access'] = 0;
      if(arg(2) == "edit") {
        $form['actions']['submit']['#submit'][] = 'artchimp_exhibitioneditsubmit';              
      }
      if(arg(0) == 'node' && arg(2) == 'edit'){
        $artist_node = node_load(arg(1));
       drupal_set_title($artist_node->title);
      }

      break;

      case "artist_node_form":
      if(arg(2) == "edit") {  
        $form['actions']['submit']['#submit'][] = '_artchimp_editsubmit';
      }
      if(arg(0) == 'node' && arg(2) == 'edit'){
        $artist_node = node_load(arg(1));
       drupal_set_title($artist_node->title);
      }
     
      break;

      case "work_node_form":
      if(arg(2) == "edit") {
        $form['actions']['submit']['#submit'][] = 'artchimp_workeditsubmit';             
      }
      if(arg(0) == 'node' && arg(2) == 'edit'){
        $artist_node = node_load(arg(1));
       drupal_set_title($artist_node->title);
      }

      break;

      case "blog_node_form":
      if(arg(2) == "edit") {
        $form['actions']['submit']['#submit'][] = 'artchimp_blogeditsubmit';
              
      }
      if(arg(0) == 'node' && arg(2) == 'edit'){
        $artist_node = node_load(arg(1));
       drupal_set_title($artist_node->title);
      }
      break;

      case "publication_node_form":
      if(arg(2) == "edit") {
        $form['actions']['submit']['#submit'][] = 'artchimp_publicationeditsubmit';              
      }
      if(arg(0) == 'node' && arg(2) == 'edit'){
        $artist_node = node_load(arg(1));
       drupal_set_title($artist_node->title);
      }

      break; 

      case "event_node_form":
      if(arg(2) == "edit") {
        $form['actions']['submit']['#submit'][] = 'artchimp_eventeditsubmit';              
      }
      if(arg(0) == 'node' && arg(2) == 'edit'){
        $event_node = node_load(arg(1));
       drupal_set_title($event_node->title);
      }

      break;   

      case "section_node_form":
      if(arg(2) == "edit") {
        $form['actions']['submit']['#submit'][] = 'artchimp_sectioneditsubmit';              
      }
      if(arg(0) == 'node' && arg(2) == 'edit'){
        $section_node = node_load(arg(1));
       drupal_set_title($section_node->title);
      }

      break;   
     } 
}

// function artchimp_user_login(&$edit, $account) {

//   if($account->roles[2] && $account->roles[4]) {
//     $edit['redirect'] = 'users/'.$account->name;
//   } else {
//   $edit['redirect'] = 'exhibitions';
//   }
// }

function _artchimp_editsubmit($form, &$form_state){
 
  $usr = node_load(arg(1));
  $name = $usr->title;
  $link = url('node/'.$usr->nid);
  drupal_get_messages('status');
  drupal_set_message(t('Artist:<a href="@link" target="_blank">%name</a> was updated',array('@link'=>$link,
  '%name'=>$name)));
  $form_state['redirect'] = 'node/' . arg(1) .'/edit';
}

function artchimp_exhibitioneditsubmit($form, &$form_state){
 
  $node_exhi = node_load(arg(1));
  if($node_exhi->type == "exhibition") {
   $title = $node_exhi->title;
   $link = url('node/'.$node_exhi->nid);
   drupal_get_messages('status');
   drupal_set_message(t('The exhibition: <a href="@link" target="_blank">%name </a> was updated.',array('@link'=>$link,
   '%name'=>$title)));
  } 

  $form_state['redirect'] = 'node/' . arg(1) .'/edit';
 
}

function artchimp_workeditsubmit($form, &$form_state){
 
  $node_artwork = node_load(arg(1));
  if($node_artwork->type == "work") {
   $title = $node_artwork->title;
   $link = url('node/'.$node_artwork->nid);
   drupal_get_messages('status');
   drupal_set_message(t('The work: <a href="@link" target="_blank">%name </a> was updated.',array('@link'=>$link,
   '%name'=>$title)));
  }  
  $form_state['redirect'] = 'node/' . arg(1) .'/edit';
 
}

function artchimp_blogeditsubmit($form, &$form_state){
 
  $node_blog = node_load(arg(1));
  if($node_blog->type == "blog") {
   $title = $node_blog->title;
   $link = url('node/'.$node_blog->nid);
   drupal_get_messages('status');
   drupal_set_message(t('The blog: <a href="@link" target="_blank">%name </a> was updated.',array('@link'=>$link,
   '%name'=>$title)));
  }  
  $form_state['redirect'] = 'node/' . arg(1) .'/edit';
 
}

function artchimp_publicationeditsubmit($form, &$form_state){
 
  $node_publication = node_load(arg(1));
  if($node_publication->type == "publication") {
   $title = $node_publication->title;
   $link = url('node/'.$node_publication->nid);
   drupal_get_messages('status');
   drupal_set_message(t('The publication: <a href="@link" target="_blank">%name </a> was updated.',array('@link'=>$link,
   '%name'=>$title)));
  }  
  $form_state['redirect'] = 'node/' . arg(1) .'/edit';
}

function artchimp_eventeditsubmit($form, &$form_state) {

  $node_event = node_load(arg(1));
  if($node_event->type == "event") {
   $title = $node_event->title;
   $link = url('node/'.$node_event->nid);
   drupal_get_messages('status');
   drupal_set_message(t('The publication: <a href="@link" target="_blank">%name </a> was updated.',array('@link'=>$link,
   '%name'=>$title)));
  }  
  $form_state['redirect'] = 'node/' . arg(1) .'/edit';
}

function artchimp_sectioneditsubmit($form, &$form_state) {
  $node_section = node_load(arg(1));
  if($node_section->type == "section") {
   $title = $node_section->title;
   $link = url('node/'.$node_section->nid);
   drupal_get_messages('status');
   drupal_set_message(t('The section: <a href="@link" target="_blank">%name </a> was updated.',array('@link'=>$link,
   '%name'=>$title)));
  }  
  $form_state['redirect'] = 'node/' . arg(1) .'/edit';
}

function artists_work_form($form, &$form_state) {
  
  $nid = arg(2);
  $node = node_load($nid);

  $default_value = array();

  if(isset($node->field_exhibition_hidden['und'])) {
    foreach ($node->field_exhibition_hidden['und'] as $k => $v) {
      $default_value[] = $v['target_id'];
    }
  }
  
  $works = array();

  $artist = node_load($nid);
  $artist_id = $artist->field_artist_id['und'];

  foreach($artist_id as $id) {
  	
  	$art_id = $id['target_id'];
  	$work = views_get_view_result('list_works','block_2', $art_id);  	
    $works = array_merge($works,$work);
  }

  $vals = array();
  foreach($works as $value) {
  $vals[$value->nid] = $value->node_title;

  $form['artist_works'] = array(
     '#type' => 'checkboxes',
     '#title' => t('Artists Works'),
     '#options' => $vals, 
     '#default_value' =>  $default_value,
     '#description' => t('Choose as many as you want'),
  );
  
}

$form['exhibition_id'] = array('#type' => 'hidden', '#value' => $nid);
$form['submit_button'] = array(
    '#type' => 'submit',
    '#value' => t('Add Work'),
  );
  return $form;
}

function form_example_form_validate($form, &$form_state) {
}


function artists_work_form_submit($form, &$form_state) {
  $exhibition_node = arg(2);
  $work_id = array_filter($form_state['values']['artist_works']);
  $work_id = array_values($work_id);
  
  $exhi_node = node_load($exhibition_node);
  $exhi_node->field_exhibition_hidden[LANGUAGE_NONE] = array();
  foreach ($work_id as $key => $value) {
    $exhi_node->field_exhibition_hidden[LANGUAGE_NONE][$key]['target_id'] = $value;
    $exhi_node->field_exhibition_hidden[LANGUAGE_NONE][$key]['target_type'] = "node";
  }
  node_save($exhi_node);
  $form_state['redirect'] = 'node/'.$exhibition_node;
  drupal_set_message(t('The form has been submitted.'));
}